### ISSUE TITLE
[Feature Request] Add a Contributors Button to the Home Page 🎨

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#158]
## Add a Contributors Button to the Home Page

We need to implement a new button on the home page that directs users to the [Contributors page](https://before-i-die-achievements.vercel.app/Contributors). Currently, users can only access this page by manually entering the URL `https://before-i-die-achievements.vercel.app/Contributors`.

### Task Details
**This issue is open to anyone interested in contributing to the project's UI.** We suggest placing the new button near the existing `GITHUB REPO` button and maintaining a consistent style in terms of appearance and functionality. However, we encourage contributors to bring their own creative flair to the design.

Please ensure the new button is easily accessible, visually appealing, and seamlessly integrated into the existing layout.

### Tips to get started 
This is a React project so you will need to add a button on the [Header.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/Header/Header.jsx) and lead the call path so that it displays the [Contributors Grid](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/Components/ContributorsGrid) component. The routing path has already been created in the [index.js](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/index.js) file using react-router-dom.

### Screenshots

<img width="1160" alt="Screenshot 2023-10-03 at 00 21 16" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/a2113d14-b109-478f-bf87-038f98985f65">
<img width="1161" alt="Screenshot 2023-10-03 at 00 21 49" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/87d65f4f-b345-4697-93b5-0c455c15980c">

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)
