### ISSUE TITLE
🟢 Hindi Translation NEEDED for Documentation

### ISSUE THREAD

**Issue by XanderRubio** [BeforeIDieCode/BeforeIDieAchievements#30]
Hindi translation is needed for the following files: 

- [x] [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/README.md) #65
- [x]  [CODE_OF_CONDUCT](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CODE_OF_CONDUCT.md)  #153 
- [x]  [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) being worked on by @abhinaba-dash 
- [x]  [LICENSE](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/LICENSE) added from pull request #35
- [x] [about.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/about.md) added from pull request #193

Please add these files in the empty [Hindi section](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/translations/Hindi).

And please work off the branch [hindi-translation](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/hindi-translation) for organization purposes.

Modeling after the [GitHub Repository first-contributors](https://github.com/firstcontributions/first-contributions)
<img width="1057" alt="Screenshot 2023-08-24 at 02 26 10" src="https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/120526253/40a7d3f7-7bcc-4173-8ff3-0173f858fa05">

**Comment by abhinaba-dash** [comment]
Hello @XanderRubio can I work upon translating contribution guidelines into hindi?

**Comment by XanderRubio** [comment]
> Hello @XanderRubio can I work upon translating contribution guidelines into hindi?

Excellent @abhinaba-dash, and I will go ahead and assign you to this issue for translating the [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md). Thank you for your enthusiasm, assistance and have a nice day!
